name: api-observatory-partition-lab

services:
  broker:
    image: redpandadata/redpanda:v24.1.1
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --overprovisioned
      - --kafka-addr
      - internal://0.0.0.0:29092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://broker:29092,external://127.0.0.1:19092
    ports:
      - "127.0.0.1:19092:19092"
