[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = is_superuser(r.sub) \
  || (g(r.sub, r.dom, r.obj) \
  && (p.dom == "*" || p.dom == r.dom) \
  && (p.obj == "*" || p.obj == r.obj) \
  && (p.act == "*" || p.act == r.act))
