"""add_agent_run_table

Revision ID: 1088e092eac2
Revises: c64a98702ec4
Create Date: 2026-07-11 16:52:50.438550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1088e092eac2'
down_revision: Union[str, Sequence[str], None] = 'c64a98702ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('root_cause_hypothesis', sa.String(length=2048), nullable=True),
    sa.Column('severity_assessment', sa.String(length=32), nullable=True),
    sa.Column('recommended_action', sa.String(length=2048), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_observation_id', 'agent_runs', ['observation_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_observation_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
