"""initial_schema

Revision ID: c64a98702ec4
Revises: 
Create Date: 2026-05-26 16:40:26.796505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64a98702ec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuse_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detection_rule', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abuse_signals_actor', 'abuse_signals', ['actor_type', 'actor_id'], unique=False)
    op.create_index('ix_abuse_signals_resolved_at', 'abuse_signals', ['resolved_at'], unique=False)
    op.create_index('ix_abuse_signals_severity', 'abuse_signals', ['severity'], unique=False)
    op.create_index('ix_abuse_signals_signal_type', 'abuse_signals', ['signal_type'], unique=False)
    op.create_index('ix_abuse_signals_tenant_id', 'abuse_signals', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('ix_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('contract_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('payload_schema', sa.JSON(), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('snapshot_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_snapshots_fingerprint', 'contract_snapshots', ['schema_fingerprint'], unique=False)
    op.create_index('ix_contract_snapshots_source_id', 'contract_snapshots', ['source_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('current_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('added_fields', sa.JSON(), nullable=False),
    sa.Column('removed_fields', sa.JSON(), nullable=False),
    sa.Column('type_changed_fields', sa.JSON(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_events_current_snapshot_id', 'drift_events', ['current_snapshot_id'], unique=False)
    op.create_index('ix_drift_events_event_type', 'drift_events', ['event_type'], unique=False)
    op.create_index('ix_drift_events_severity', 'drift_events', ['severity'], unique=False)
    op.create_index('ix_drift_events_source_id', 'drift_events', ['source_id'], unique=False)
    op.create_table('inbox_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_name', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', 'message_id', name='uq_inbox_consumptions_consumer_message')
    )
    op.create_index('ix_inbox_consumptions_consumer_name', 'inbox_consumptions', ['consumer_name'], unique=False)
    op.create_index('ix_inbox_consumptions_processed_at', 'inbox_consumptions', ['processed_at'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'timestamp', name='uq_observations_source_timestamp')
    )
    op.create_index('ix_observations_active_source', 'observations', ['source'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_observations_processed', 'observations', ['processed'], unique=False)
    op.create_index('ix_observations_timestamp', 'observations', ['timestamp'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_events_idempotency_key', 'outbox_events', ['idempotency_key'], unique=True)
    op.create_index('ix_outbox_events_published_at', 'outbox_events', ['published_at'], unique=False)
    op.create_index('ix_outbox_events_tenant_id', 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kafka_topic', sa.String(length=255), nullable=False),
    sa.Column('kafka_partition', sa.Integer(), nullable=False),
    sa.Column('kafka_offset', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('dead_letter_queue', sa.Boolean(), nullable=False),
    sa.Column('dlq_reason', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_dead_letter_queue', 'processed_events', ['dead_letter_queue'], unique=False)
    op.create_index('ix_events_idempotency_key', 'processed_events', ['idempotency_key'], unique=True)
    op.create_index('ix_events_kafka_offset', 'processed_events', ['kafka_offset'], unique=False)
    op.create_index('ix_events_status', 'processed_events', ['status'], unique=False)
    op.create_table('provider_health_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phs_sampled_at', 'provider_health_samples', ['sampled_at'], unique=False)
    op.create_index('ix_phs_source_id', 'provider_health_samples', ['source_id'], unique=False)
    op.create_index('ix_phs_source_sampled', 'provider_health_samples', ['source_id', 'sampled_at'], unique=False)
    op.create_index('ix_phs_tenant_id', 'provider_health_samples', ['tenant_id'], unique=False)
    op.create_table('security_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_audit_events_actor_id', 'security_audit_events', ['actor_id'], unique=False)
    op.create_index('ix_security_audit_events_actor_type', 'security_audit_events', ['actor_type'], unique=False)
    op.create_index('ix_security_audit_events_created_at', 'security_audit_events', ['created_at'], unique=False)
    op.create_index('ix_security_audit_events_event_type', 'security_audit_events', ['event_type'], unique=False)
    op.create_index('ix_security_audit_events_tenant_id', 'security_audit_events', ['tenant_id'], unique=False)
    op.create_table('source_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('health_check_path', sa.String(length=255), nullable=False),
    sa.Column('probe_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_profiles_active', 'source_profiles', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_source_profiles_name', 'source_profiles', ['name'], unique=True)
    op.create_table('user_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_index(op.f('ix_user_tenants_tenant_id'), 'user_tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenants_user_id'), 'user_tenants', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_tenants_user_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_tenant_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index('ix_source_profiles_name', table_name='source_profiles')
    op.drop_index('ix_source_profiles_active', table_name='source_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_table('source_profiles')
    op.drop_index('ix_security_audit_events_tenant_id', table_name='security_audit_events')
    op.drop_index('ix_security_audit_events_event_type', table_name='security_audit_events')
    op.drop_index('ix_security_audit_events_created_at', table_name='security_audit_events')
    op.drop_index('ix_security_audit_events_actor_type', table_name='security_audit_events')
    op.drop_index('ix_security_audit_events_actor_id', table_name='security_audit_events')
    op.drop_table('security_audit_events')
    op.drop_index('ix_phs_tenant_id', table_name='provider_health_samples')
    op.drop_index('ix_phs_source_sampled', table_name='provider_health_samples')
    op.drop_index('ix_phs_source_id', table_name='provider_health_samples')
    op.drop_index('ix_phs_sampled_at', table_name='provider_health_samples')
    op.drop_table('provider_health_samples')
    op.drop_index('ix_events_status', table_name='processed_events')
    op.drop_index('ix_events_kafka_offset', table_name='processed_events')
    op.drop_index('ix_events_idempotency_key', table_name='processed_events')
    op.drop_index('ix_events_dead_letter_queue', table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_events_tenant_id', table_name='outbox_events')
    op.drop_index('ix_outbox_events_published_at', table_name='outbox_events')
    op.drop_index('ix_outbox_events_idempotency_key', table_name='outbox_events')
    op.drop_index('ix_outbox_events_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_observations_timestamp', table_name='observations')
    op.drop_index('ix_observations_processed', table_name='observations')
    op.drop_index('ix_observations_active_source', table_name='observations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('observations')
    op.drop_index('ix_inbox_consumptions_processed_at', table_name='inbox_consumptions')
    op.drop_index('ix_inbox_consumptions_consumer_name', table_name='inbox_consumptions')
    op.drop_table('inbox_consumptions')
    op.drop_index('ix_drift_events_source_id', table_name='drift_events')
    op.drop_index('ix_drift_events_severity', table_name='drift_events')
    op.drop_index('ix_drift_events_event_type', table_name='drift_events')
    op.drop_index('ix_drift_events_current_snapshot_id', table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index('ix_contract_snapshots_source_id', table_name='contract_snapshots')
    op.drop_index('ix_contract_snapshots_fingerprint', table_name='contract_snapshots')
    op.drop_table('contract_snapshots')
    op.drop_index('ix_api_keys_tenant_id', table_name='api_keys')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_is_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_abuse_signals_tenant_id', table_name='abuse_signals')
    op.drop_index('ix_abuse_signals_signal_type', table_name='abuse_signals')
    op.drop_index('ix_abuse_signals_severity', table_name='abuse_signals')
    op.drop_index('ix_abuse_signals_resolved_at', table_name='abuse_signals')
    op.drop_index('ix_abuse_signals_actor', table_name='abuse_signals')
    op.drop_table('abuse_signals')
    # ### end Alembic commands ###
