events {}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    upstream replicas {
        server replica-a:8080 max_fails=1 fail_timeout=3s;
        server replica-b:8080 max_fails=1 fail_timeout=3s;
        server replica-c:8080 max_fails=1 fail_timeout=3s;
    }

    server {
        listen 8080;

        location / {
            proxy_connect_timeout 500ms;
            proxy_read_timeout 2s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_pass http://replicas;
        }
    }
}
