"""create_indexed_documents

Revision ID: 1252358c354c
Revises:
Create Date: 2026-07-11 22:47:21.890392

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1252358c354c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Install pgvector before creating the table that uses its vector type."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "indexed_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection",
            "external_id",
            name="uq_indexed_documents_collection_external_id",
        ),
    )
    op.create_index(
        "ix_indexed_documents_collection",
        "indexed_documents",
        ["collection"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_indexed_documents_collection", table_name="indexed_documents")
    op.drop_table("indexed_documents")
    # ### end Alembic commands ###
