apiVersion: v1
kind: ConfigMap
metadata:
  name: api-obs-app-config
  labels:
    app.kubernetes.io/part-of: api-obs
data:
  ingestor_url: http://ingestor:8000
  service_version: "0.1.0"
  trusted_hosts: ingestor,ingestor.127.0.0.1.nip.io
