apiVersion: v1
kind: Service
metadata:
  name: ingestor-db
  labels:
    app.kubernetes.io/name: ingestor-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: api-obs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingestor-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
