apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-obs
resources:
  - namespace.yaml
  - service-account.yaml
  - config.yaml
  - secret.yaml
  - postgres-init-configmap.yaml
  - ingestor-db-deployment.yaml
  - ingestor-db-service.yaml
  - ingestor-deployment.yaml
  - ingestor-service.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - ingress.yaml
