[theme]
baseFontSize = 12
# font = "sans-serif"
# headingFont = "sans-serif"
# codeFont = "monospace"
# codeFontSize = "0.8rem"
# primaryColor = "#ff4b4b"

# [theme.sidebar]
# font = "sans-serif"
# headingFont = "sans-serif"
# codeFont = "monospace"
